version: '2.3'

services:

# glutton service
  glutton:
    build: .
    container_name: glutton
    restart: always
    tmpfs:
     - /var/lib/glutton:uid=2000,gid=2000
     - /run:uid=2000,gid=2000
    network_mode: "host"
    cap_add:
     - NET_ADMIN
    image: "vhoney/glutton:2.0"
    read_only: true
    volumes:
     - /data/glutton/log:/var/log/glutton
     - /root/vhoney/docker/glutton/dist/rules.yaml:/opt/glutton/rules/rules.yaml
